# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable underglow
CONFIG_WS2812_STRIP_RPI_PICO_PIO=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=16
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=263

# Disable unused options
CONFIG_SPI=n

# Turn on logging, and set ZMK logging to debug output
# CONFIG_LOG=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_ZMK_LOG_LEVEL_DBG=y
# CONFIG_LOG_BUFFER_SIZE=20000
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
